In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('results.csv')
df

,condition_id,agent_type,agent_label,task_id,task_type,server,execution_mode,server_load_level,servers,repetition,...,total_latency_ms,tool_call_count,tool_call_success_count,tool_call_success_rate,tool_selection_correctness,task_success,task_grade,response_length,trace_event_count,completed_at
0,A1_T1-MCP-1_minimal_r1,mcp,A1,T1-MCP-1,T1,morse,MCP,minimal,morse,1,...,13114.076375,1,1,1.0,1.0,True,1.00,134,4,2026-03-13T18:16:46.742757+00:00
1,A2_T1-MCP-1_minimal_r1,code_mode,A2,T1-MCP-1,T1,morse,MCP,minimal,morse,1,...,9217.278000,3,3,1.0,0.0,True,0.90,280,10,2026-03-13T18:17:03.135858+00:00
2,A3_T1-MCP-1_minimal_r1,multi_agent_mcp,A3,T1-MCP-1,T1,morse,MCP,minimal,morse,1,...,7345.312583,2,2,1.0,1.0,True,1.00,147,10,2026-03-13T18:17:14.814378+00:00
3,A4_T1-MCP-1_minimal_r1,multi_agent_code,A4,T1-MCP-1,T1,morse,MCP,minimal,morse,1,...,15692.314292,4,4,1.0,0.0,True,1.00,264,16,2026-03-13T18:17:37.936573+00:00
4,A1_T1-MCP-2_minimal_r1,mcp,A1,T1-MCP-2,T1,morse,MCP,minimal,morse,1,...,4250.800042,1,1,1.0,1.0,True,1.00,353,4,2026-03-13T18:17:46.286749+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,A3_T2-MCP-3_moderate_r1,multi_agent_mcp,A3,T2-MCP-3,T2,cross_server,MCP,moderate,lastfm;devtoolkit;postgres,1,...,38326.339101,6,6,1.0,1.0,True,0.90,740,25,2026-03-19T06:02:51.532750+00:00
380,A3_T2-MCP-3_maximal_r1,multi_agent_mcp,A3,T2-MCP-3,T2,cross_server,MCP,maximal,lastfm;devtoolkit;postgres,1,...,39020.185142,4,4,1.0,1.0,True,0.95,892,19,2026-03-19T06:03:38.732681+00:00
381,A4_T2-MCP-3_minimal_r1,multi_agent_code,A4,T2-MCP-3,T2,cross_server,MCP,minimal,lastfm;devtoolkit,1,...,94158.016834,10,10,1.0,0.0,False,0.60,1466,34,2026-03-19T06:05:24.259564+00:00
382,A4_T2-MCP-3_moderate_r1,multi_agent_code,A4,T2-MCP-3,T2,cross_server,MCP,moderate,lastfm;devtoolkit;postgres,1,...,217542.218390,18,18,1.0,0.0,False,0.40,3562,61,2026-03-19T06:09:13.762397+00:00
383,A4_T2-MCP-3_maximal_r1,multi_agent_code,A4,T2-MCP-3,T2,cross_server,MCP,maximal,lastfm;devtoolkit;postgres,1,...,59193.711776,8,8,1.0,0.0,True,0.95,1608,28,2026-03-19T06:10:24.907333+00:00

In [4]:
df.describe()

,repetition,temperature,error,input_tokens,output_tokens,total_tokens,total_latency_ms,tool_call_count,tool_call_success_count,tool_call_success_rate,tool_selection_correctness,task_grade,response_length,trace_event_count
count,384.0,3.840000e+02,0.0,3.840000e+02,384.000000,3.840000e+02,3.840000e+02,384.000000,384.000000,384.000000,384.000000,384.000000,384.000000,384.000000
mean,1.0,2.000000e-01,NaN,6.495148e+04,3074.648438,6.802612e+04,5.855429e+04,7.338542,7.330729,0.999067,0.473958,0.666146,1037.036458,22.856771
std,0.0,2.779179e-17,NaN,1.201720e+05,6055.838899,1.259417e+05,9.122094e+04,7.512216,7.510306,0.011138,0.499973,0.336158,603.387966,16.900502
min,1.0,2.000000e-01,NaN,1.345000e+03,102.000000,1.497000e+03,4.221259e+03,1.000000,1.000000,0.833333,0.000000,0.000000,54.000000,4.000000
25%,1.0,2.000000e-01,NaN,1.093050e+04,597.750000,1.190575e+04,1.514627e+04,3.000000,3.000000,1.000000,0.000000,0.300000,594.500000,10.000000
50%,1.0,2.000000e-01,NaN,2.582250e+04,1207.000000,2.682750e+04,2.955958e+04,5.000000,5.000000,1.000000,0.000000,0.750000,1001.500000,19.000000
75%,1.0,2.000000e-01,NaN,7.906725e+04,3635.000000,8.121175e+04,7.397020e+04,10.000000,10.000000,1.000000,1.000000,1.000000,1418.500000,31.000000
max,1.0,2.000000e-01,NaN,1.739368e+06,94986.000000,1.834354e+06,1.347838e+06,84.000000,84.000000,1.000000,1.000000,1.000000,3562.000000,94.000000

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 384 entries, 0 to 383
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   condition_id                384 non-null    str
 1   agent_type                  384 non-null    str
 2   agent_label                 384 non-null    str
 3   task_id                     384 non-null    str
 4   task_type                   384 non-null    str
 5   server                      384 non-null    str
 6   execution_mode              384 non-null    str
 7   server_load_level           384 non-null    str
 8   servers                     384 non-null    str
 9   repetition                  384 non-null    int64
 10  model_id                    384 non-null    str
 11  temperature                 384 non-null    float64
 12  success                     384 non-null    bool
 13  error                       0 non-null      float64
 14  input_tokens                384 non-null    int64
 15  output_tokens               384 non-null    int64
 16  total_tokens                384 non-null    int64
 17  total_latency_ms            384 non-null    float64
 18  tool_call_count             384 non-null    int64
 19  tool_call_success_count     384 non-null    int64
 20  tool_call_success_rate      384 non-null    float64
 21  tool_selection_correctness  384 non-null    float64
 22  task_success                384 non-null    bool
 23  task_grade                  384 non-null    float64
 24  response_length             384 non-null    int64
 25  trace_event_count           384 non-null    int64
 26  completed_at                384 non-null    str
dtypes: bool(2), float64(6), int64(8), str(11)
memory usage: 75.9 KB

In [9]:
df['execution_mode'].nunique()

1

In [26]:
numeric_cols = df.select_dtypes(include="number").columns.drop(['repetition','temperature'], errors="ignore")
details = df.groupby(['agent_type','server'])['total_tokens'].agg(['mean','sum']).reset_index()
details['mode'] = details['agent_type'].apply(lambda x: 'code' if (x=='code_mode' or x=='multi_agent_code') else 'mcp')
details['archi'] = details['agent_type'].apply(lambda x: 'multi' if (x=='multi_agent_mcp' or x=='multi_agent_code') else 'single')
details

          agent_type        server           mean      sum  mode   archi
0          code_mode  alphavantage  225221.000000  1126105  code  single
1          code_mode     cocktails   44843.200000   224216  code  single
2          code_mode  cross_server   95815.444444   862339  code  single
3          code_mode    devtoolkit   13555.875000   108447  code  single
4          code_mode        lastfm  148026.296296  3996710  code  single
5          code_mode         morse   11986.800000    59934  code  single
6          code_mode          nasa  146215.200000   731076  code  single
7          code_mode     nutrition   49466.400000   247332  code  single
8          code_mode      postgres   78195.074074  2111267  code  single
9                mcp  alphavantage    8652.400000    43262   mcp  single
10               mcp     cocktails    8050.200000    40251   mcp  single
11               mcp  cross_server   33754.222222   303788   mcp  single
12               mcp    devtoolkit   18931.875000   151455   mcp  single
13               mcp        lastfm   15438.333333   416835   mcp  single
14               mcp         morse    1565.800000     7829   mcp  single
15               mcp          nasa  103739.400000   518697   mcp  single
16               mcp     nutrition   16552.200000    82761   mcp  single
17               mcp      postgres   23970.851852   647213   mcp  single
18  multi_agent_code  alphavantage   70747.400000   353737  code   multi
19  multi_agent_code     cocktails   49959.200000   249796  code   multi
20  multi_agent_code  cross_server   85400.555556   768605  code   multi
21  multi_agent_code    devtoolkit   18046.250000   144370  code   multi
22  multi_agent_code        lastfm  236535.407407  6386456  code   multi
23  multi_agent_code         morse    9638.800000    48194  code   multi
24  multi_agent_code          nasa  125136.000000   625680  code   multi
25  multi_agent_code     nutrition   33765.200000   168826  code   multi
26  multi_agent_code      postgres  133696.555556  3609807  code   multi
27   multi_agent_mcp  alphavantage    9960.000000    49800   mcp   multi
28   multi_agent_mcp     cocktails   11294.200000    56471   mcp   multi
29   multi_agent_mcp  cross_server   23958.222222   215624   mcp   multi
30   multi_agent_mcp    devtoolkit   20187.750000   161502   mcp   multi
31   multi_agent_mcp        lastfm   16693.518519   450725   mcp   multi
32   multi_agent_mcp         morse    2883.400000    14417   mcp   multi
33   multi_agent_mcp          nasa  105406.600000   527033   mcp   multi
34   multi_agent_mcp     nutrition   16248.000000    81240   mcp   multi
35   multi_agent_mcp      postgres   19638.222222   530232   mcp   multi

In [32]:
comparison = details.groupby(['server', 'mode','archi'])['mean'].first()
comparison.reset_index()

          server  mode   archi           mean
0   alphavantage  code   multi   70747.400000
1   alphavantage  code  single  225221.000000
2   alphavantage   mcp   multi    9960.000000
3   alphavantage   mcp  single    8652.400000
4      cocktails  code   multi   49959.200000
5      cocktails  code  single   44843.200000
6      cocktails   mcp   multi   11294.200000
7      cocktails   mcp  single    8050.200000
8   cross_server  code   multi   85400.555556
9   cross_server  code  single   95815.444444
10  cross_server   mcp   multi   23958.222222
11  cross_server   mcp  single   33754.222222
12    devtoolkit  code   multi   18046.250000
13    devtoolkit  code  single   13555.875000
14    devtoolkit   mcp   multi   20187.750000
15    devtoolkit   mcp  single   18931.875000
16        lastfm  code   multi  236535.407407
17        lastfm  code  single  148026.296296
18        lastfm   mcp   multi   16693.518519
19        lastfm   mcp  single   15438.333333
20         morse  code   multi    9638.800000
21         morse  code  single   11986.800000
22         morse   mcp   multi    2883.400000
23         morse   mcp  single    1565.800000
24          nasa  code   multi  125136.000000
25          nasa  code  single  146215.200000
26          nasa   mcp   multi  105406.600000
27          nasa   mcp  single  103739.400000
28     nutrition  code   multi   33765.200000
29     nutrition  code  single   49466.400000
30     nutrition   mcp   multi   16248.000000
31     nutrition   mcp  single   16552.200000
32      postgres  code   multi  133696.555556
33      postgres  code  single   78195.074074
34      postgres   mcp   multi   19638.222222
35      postgres   mcp  single   23970.851852

In [ ]:
comparison = details.groupby(['server', 'mode','archi'])['mean'].first()
res = comparison.reset_index()
pls = res.groupby(['server','archi'])['mean'].idxmax().reset_index().rename()
res.loc[pls]

          server  mode   archi           mean
0   alphavantage  code   multi   70747.400000
1   alphavantage  code  single  225221.000000
4      cocktails  code   multi   49959.200000
5      cocktails  code  single   44843.200000
8   cross_server  code   multi   85400.555556
9   cross_server  code  single   95815.444444
14    devtoolkit   mcp   multi   20187.750000
15    devtoolkit   mcp  single   18931.875000
16        lastfm  code   multi  236535.407407
17        lastfm  code  single  148026.296296
20         morse  code   multi    9638.800000
21         morse  code  single   11986.800000
24          nasa  code   multi  125136.000000
25          nasa  code  single  146215.200000
28     nutrition  code   multi   33765.200000
29     nutrition  code  single   49466.400000
32      postgres  code   multi  133696.555556
33      postgres  code  single   78195.074074

In [2]:
import pandas as pd

df = pd.read_csv('post_fix_merged.csv')
df

,condition_id,agent_type,agent_label,task_id,task_type,server,execution_mode,server_load_level,servers,repetition,...,total_latency_ms,tool_call_count,tool_call_success_count,tool_call_success_rate,tool_selection_correctness,task_success,task_grade,response_length,trace_event_count,completed_at
0,A1_T1-MCP-1_minimal_r1,mcp,A1,T1-MCP-1,T1,lastfm,MCP,minimal,lastfm,1,...,10551.677837,1,1,1.0,1.0,True,1.0,1379,4,2026-03-20T01:21:35.992533+00:00
1,A1_T1-MCP-1_moderate_r1,mcp,A1,T1-MCP-1,T1,lastfm,MCP,moderate,lastfm;postgres,1,...,10262.413421,1,1,1.0,1.0,True,1.0,1379,4,2026-03-20T01:21:54.079773+00:00
2,A1_T1-MCP-1_maximal_r1,mcp,A1,T1-MCP-1,T1,lastfm,MCP,maximal,lastfm;postgres,1,...,9922.764962,1,1,1.0,1.0,True,1.0,1272,4,2026-03-20T01:22:10.329849+00:00
3,A2_T1-MCP-1_minimal_r1,code_mode,A2,T1-MCP-1,T1,lastfm,MCP,minimal,lastfm,1,...,19649.515925,3,3,1.0,0.0,False,0.5,1388,10,2026-03-20T01:22:38.625628+00:00
4,A2_T1-MCP-1_moderate_r1,code_mode,A2,T1-MCP-1,T1,lastfm,MCP,moderate,lastfm;postgres,1,...,18138.217175,3,3,1.0,0.0,False,0.5,1432,10,2026-03-20T01:23:06.387343+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,A3_T2-MCP-5_moderate_r1,multi_agent_mcp,A3,T2-MCP-5,T2,nutrition,MCP,moderate,nutrition;alphavantage;cocktails,1,...,18648.631400,5,5,1.0,1.0,True,1.0,395,19,2026-03-20T22:40:51.606076+00:00
644,A3_T2-MCP-5_maximal_r1,multi_agent_mcp,A3,T2-MCP-5,T2,nutrition,MCP,maximal,nutrition;alphavantage;cocktails;devtoolkit;mo...,1,...,11220.237700,3,3,1.0,1.0,True,1.0,379,13,2026-03-20T22:41:15.193976+00:00
645,A4_T2-MCP-5_minimal_r1,multi_agent_code,A4,T2-MCP-5,T2,nutrition,MCP,minimal,nutrition,1,...,21995.802500,4,4,1.0,0.0,False,0.3,579,16,2026-03-20T22:41:46.160447+00:00
646,A4_T2-MCP-5_moderate_r1,multi_agent_code,A4,T2-MCP-5,T2,nutrition,MCP,moderate,nutrition;alphavantage;cocktails,1,...,23782.023400,5,5,1.0,0.0,False,0.3,432,19,2026-03-20T22:42:20.842091+00:00
647,A4_T2-MCP-5_maximal_r1,multi_agent_code,A4,T2-MCP-5,T2,nutrition,MCP,maximal,nutrition;alphavantage;cocktails;devtoolkit;mo...,1,...,24616.160600,5,5,1.0,0.0,False,0.3,611,19,2026-03-20T22:42:58.247535+00:00

In [4]:
df['server'].value_counts()

server
lastfm          108
postgres        108
devtoolkit       96
alphavantage     60
cocktails        60
morse            60
nasa             60
nutrition        60
cross_server     36
Name: count, dtype: int64

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 648 entries, 0 to 647
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   condition_id                648 non-null    str
 1   agent_type                  648 non-null    str
 2   agent_label                 648 non-null    str
 3   task_id                     648 non-null    str
 4   task_type                   648 non-null    str
 5   server                      648 non-null    str
 6   execution_mode              648 non-null    str
 7   server_load_level           648 non-null    str
 8   servers                     648 non-null    str
 9   repetition                  648 non-null    int64
 10  model_id                    648 non-null    str
 11  temperature                 648 non-null    float64
 12  success                     648 non-null    bool
 13  error                       0 non-null      float64
 14  input_tokens                648 non-null    int64
 15  output_tokens               648 non-null    int64
 16  total_tokens                648 non-null    int64
 17  total_latency_ms            648 non-null    float64
 18  tool_call_count             648 non-null    int64
 19  tool_call_success_count     648 non-null    int64
 20  tool_call_success_rate      648 non-null    float64
 21  tool_selection_correctness  648 non-null    float64
 22  task_success                648 non-null    bool
 23  task_grade                  648 non-null    float64
 24  response_length             648 non-null    int64
 25  trace_event_count           648 non-null    int64
 26  completed_at                648 non-null    str
dtypes: bool(2), float64(6), int64(8), str(11)
memory usage: 128.0 KB

In [8]:
res = df.groupby(['agent_type','server']).agg(
    input_tokens = ('input_tokens', 'sum'),
    output_tokens = ('output_tokens', 'sum'),
    total_tokens = ('total_tokens', 'sum')
).reset_index()
res.sort_values(by='server')

          agent_type        server  input_tokens  output_tokens  total_tokens
0          code_mode  alphavantage        399672          22589        422261
9                mcp  alphavantage        315729           4963        320692
27   multi_agent_mcp  alphavantage         90245           8869         99114
18  multi_agent_code  alphavantage        330448          31340        361788
28   multi_agent_mcp     cocktails        157545          16880        174425
1          code_mode     cocktails        620321          21249        641570
10               mcp     cocktails        351818           7848        359666
19  multi_agent_code     cocktails        436231          30090        466321
29   multi_agent_mcp  cross_server        165309          10913        176222
2          code_mode  cross_server        547857          19361        567218
11               mcp  cross_server        297304           6626        303930
20  multi_agent_code  cross_server        582603          29691        612294
30   multi_agent_mcp    devtoolkit        486436           7601        494037
12               mcp    devtoolkit        551059           3780        554839
3          code_mode    devtoolkit        261322          11010        272332
21  multi_agent_code    devtoolkit        249015          16992        266007
22  multi_agent_code        lastfm       1228614          57243       1285857
31   multi_agent_mcp        lastfm        414243          23525        437768
13               mcp        lastfm        414868          14049        428917
4          code_mode        lastfm       1520444          39777       1560221
14               mcp         morse        152933           2776        155709
23  multi_agent_code         morse        149498           9322        158820
32   multi_agent_mcp         morse         43283           5526         48809
5          code_mode         morse        183043           5998        189041
33   multi_agent_mcp          nasa       2248081          14989       2263070
24  multi_agent_code          nasa       1970768          36002       2006770
6          code_mode          nasa       2351748          32049       2383797
15               mcp          nasa       1690924           8027       1698951
16               mcp     nutrition        626376          17376        643752
7          code_mode     nutrition        655244          40131        695375
25  multi_agent_code     nutrition        665503          33200        698703
34   multi_agent_mcp     nutrition        243059          21930        264989
17               mcp      postgres        597302          20938        618240
8          code_mode      postgres       2040399          77708       2118107
26  multi_agent_code      postgres       3356666         146254       3502920
35   multi_agent_mcp      postgres        490533          47599        538132

In [9]:
df.to_csv('res_servers_types.csv')